#!/usr/bin/env node
"use strict";
var path = require("path");
var execSync = require("child_process").execSync;
var hook = path.basename(__filename);
var config = require(path.resolve(process.cwd(), "package"));

if (!config.scripts[hook]) {
  process.exit(0);
}

try {
  execSync(config.scripts[hook], {
    encoding: "utf-8",
    stdio: "inherit"
  });
} catch (error) {
  process.exit(error.status);
}
